services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - www:/var/www/html
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - sock:/run/php
    links:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - www:/var/www/html
      - sock:/run/php
      - $PWD/phptest.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

volumes:
  sock:
    driver: local
  www:
    driver: local
